### ISSUE TITLE
Zig code doesn't compile

### ISSUE THREAD

**Issue by marcinmachura** [bddicken/languages#430]
Latest Zig compiler (0.15.1) has different StdLib and existing Zig Code is not compatibile with it

Compiling Zig
zig build --build-file zig/build.zig --prefix ${PWD}/zig/zig-out --cache-dir ${PWD}/zig/.zig-cache --release=fast
zig/build.zig:16:10: error: no field named 'root_source_file' in struct 'Build.ExecutableOptions'
        .root_source_file = b.path("run.zig"),
         ^~~~~~~~~~~~~~~~
/usr/local/zig/lib/std/Build.zig:771:31: note: struct declared here
pub const ExecutableOptions = struct {
                              ^~~~~~
referenced by:
    runBuild__anon_23418: /usr/local/zig/lib/std/Build.zig:2214:33
    main: /usr/local/zig/lib/compiler/build_runner.zig:366:29
    5 reference(s) hidden; use '-freference-trace=7' to see all references
Failed to compile Zig with command: zig build --build-file zig/build.zig --prefix ${PWD}/zig/zig-out --cache-dir ${PWD}/zig/.zig-cache --release=fast

**Comment by bluelightspirit** [comment]
For me it only works with Zig 0.13.0. Zig 0.14.0 and Zig 0.16.0 did not work for me either.
